### ISSUE TITLE
Shall we make a Slack channel?

### ISSUE THREAD

**Issue by pikesley** [opendataboardgame/game#1]
It's working quite well for asynchronous chat with my band. It's also Hipster as f*ck.

@ellenbroad, any thoughts?

https://slack.com/

**Comment by ellenbroad** [comment]
You had me at "hipster". 

Also Julie was talking about it at the offsite, she said good things. My q: where does the Slack channel go?

**Comment by pikesley** [comment]
@ellenbroad Go here https://theodi.slack.com/messages/boardgame/

And then 'Create account', using your ODI email address

**Comment by pikesley** [comment]
Channel exists
