### ISSUE TITLE
Typo? Landpoint Investments / Insights?

### ISSUE THREAD

**Issue by Stephen-Gates** [opendataboardgame/game#43]
Pongy Peter's Pond event card has Natalie Pemberton-Smith as CEO of "Landpoint Insights".

Smells Fishy event card has Natalie Pemberton-Smith as CEO of "Landpoint Investments".

**Comment by ellenbroad** [comment]
Thanks @Stephen-Gates have updated the file here: https://docs.google.com/spreadsheets/d/1f4_DBOARSDj8Cfkh_fAHyjNzVKvS7ivpU0nnx4PgrOQ/edit#gid=865030394 will see if I can upload too.

**Comment by ellenbroad** [comment]
have replaced file.
