### ISSUE TITLE
Missing tiles

### ISSUE THREAD

**Issue by Kilneana** [opendataboardgame/game#44]
Hi Ellen,

I think you don't published the "private data tiles" - or I'm blind and I don't find them ^^ 
Furthermore - is the new artwork for the "open data tiles" correct? It Looks quite different in your documentation. 

Thanks
Kilneana

**Comment by ellenbroad** [comment]
@Kilneana the private data tiles aren't published, @JeniT is on holidays until Monday and will publish them then. Re the open data tiles, the artwork hasn't changed, still the same as instructions. Could you be looking at the closed side of the tiles?

**Comment by ellenbroad** [comment]
![upload_3_4_2016_at_04_40_39](https://cloud.githubusercontent.com/assets/9429639/17764412/f7a63654-6516-11e6-999e-456d54c01b86.png)

**Comment by ellenbroad** [comment]
Open tile ^

**Comment by Kilneana** [comment]
Thats the Artwork I'm missing actually - When I took a look into your tiles Folder, I get this Image by klicking on health-open.png
![health-open](https://cloud.githubusercontent.com/assets/18414390/17767925/41db15d0-6532-11e6-9e71-af4d8cd9adef.png)

**Comment by ellenbroad** [comment]
@Kilneana ah, that's the old artwork for open. Sorry, I didn't actually check :/. The mechanics are still the same, the artwork is just slightly different for closed and open. I can talk to @JeniT about uploading the new artwork next week.

**Comment by Kilneana** [comment]
Thanks for that :)

Edit: I actually made my own "private data tiles" - I can post them here, if you are interested in -> Looks Close to the tiles in the documentation.

**Comment by Kilneana** [comment]
@ellenbroad @JeniT Still waiting for the beloved update of those wonderful data tiles (open and private) :)
